services:
  web:
    depends_on:
      - database
    image: peachporn/peach
    ports:
      - 80:3000
    environment:
      DB_USER: peach
      DB_PASSWORD: peach
      DB_DATABASE: peach
      DB_HOST: database
      DB_PORT: 5432
      LIBRARY_PATH: /mnt/library
    volumes:
      - /mnt/user/appdata/peach:/mnt/library
      - /mnt/user/Porn/Movies:/mnt/media

  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: peach
      POSTGRES_PASSWORD: peach
      POSTGRES_DB: peach
    volumes:
      - /mnt/user/appdata/peach-db:/var/lib/postgresql/data/
