/*
 * This file is automatically generated from 'yarn generate-types'
 * via the codegen-index-plugin.js
 *
 * do not edit this file manually!
 */

import { typeDef as movie } from './movie.gql';

export const typeDefs = [movie];
