/*
 * This file is automatically generated from 'yarn generate-types'
 * via the codegen-index-plugin.js
 *
 * do not edit this file manually!
 */

import { typeDef as createMovie } from './movie/createMovie.gql';
import { typeDef as movie } from './movie/movie.gql';
import { typeDef as setup } from './settings/setup.gql';
import { typeDef as voume } from './volume/voume.gql';

export const typeDefs = [createMovie, movie, setup, voume];
