/*
 * This file is automatically generated from 'yarn generate-types'
 * via the codegen-index-plugin.js
 *
 * do not edit this file manually!
 */

import { resolver as movie } from './movie';

export const resolvers = [movie];
