/*
 * This file is automatically generated from 'yarn generate-types'
 * via the codegen-index-plugin.js
 *
 * do not edit this file manually!
 */

import { resolver as movie } from './movie';
import { resolver as settings } from './settings';
import { resolver as volume } from './volume';

export const resolvers = [movie, settings, volume];
